version: '2'
services:
    firstproject-app:
        image: firstproject
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://firstproject-mysql:3306/firstproject?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    firstproject-mysql:
        extends:
            file: mysql.yml
            service: firstproject-mysql
